config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users

  resources :posts

  root 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post

  belongs_to :author, class_name: User, foreign_key: :author_id

  validates :body, presence: true
  validates :author, presence: true
  validates :post, presence: true

  default_scope -> { order created_at: :desc }
  def byline
    "By #{author.email} - #{created_at}"
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  belongs_to :author, class_name: User, foreign_key: :author_id

  validates :title, presence: true
  validates :body, presence: true
  validates :author_id, presence: true

  default_scope -> { order(publish_date: :desc) }


  def byline
    "By #{author.email} - #{publish_date}"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        new_comment
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
        format.js {}
      else
        @edit_comment = @comment
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
        format.js {}
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def new_comment
    @edit_comment = Comment.new author: current_user, post: @comment.post
  end

  # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:author_id, :post_id, :body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.page(params[:page]).per(3)
    new_post
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    new_comment
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    @edit_post = @post
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        new_post
        format.html {redirect_to @post, notice: 'Post was successfully created.'}
        format.json {render :show, status: :created, location: @post}
        format.js {}
      else
        @edit_post = @post
        format.html {render :index}
        format.json {render json: @post.errors, status: :unprocessable_entity}
        format.js {}
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html {redirect_to @post, notice: 'Post was successfully updated.'}
        format.json {render :show, status: :ok, location: @post}
        format.js {}
      else
        format.html {render :edit}
        format.json {render json: @post.errors, status: :unprocessable_entity}
        format.js {}
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html {redirect_to posts_url, notice: 'Post was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

  def new_post
    @edit_post = Post.new author: current_user, publish_date: DateTime.now
  end

  def new_comment
    return unless @post
    @edit_comment = Comment.new post: @post, author: current_user
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
    @comments = @post.comments.page(params[:page]).per(5)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:title, :body, :author_id, :publish_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<article class="panel panel-default">
    <div class="panel-body"><%= comment.body.gsub("\n", '<br/>').html_safe %></div>
  <div class="panel-footer"><%= comment.author.email %><br/><%= comment.created_at %></div>
</article>

app/views/comments/_comments_panel.html.erb
<%= paginate comments, remote: true, :theme => 'twitter-bootstrap-3' %>

<%= render comments, spacer: '<hr/>' %>

app/views/comments/_form.html.erb
<%= form_for(@comment, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @comment.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h4>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :author, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :author, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :post, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :post, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :body, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :body, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/comments/_new.html.erb
<%= form_for(@edit_comment, html: { class: "col-md-6 form-horizontal", role: "form" }, remote: true) do |f| %>
    <% if @edit_comment.errors.any? %>
        <div class="alert alert-danger alert-dismissable" role="alert">
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4><%= pluralize(@edit_comment.errors.count, "error") %> prohibited this comment from being saved:</h4>

          <ul>
            <% @edit_comment.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
    <div class="form-group">
      <%= f.label :comment, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :body, class: "form-control" %>
      </div>
    </div>
      <%= f.hidden_field :author_id %>
      <%= f.hidden_field :post_id %>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: "btn btn-primary" %>
      </div>
    </div>
<% end %>

app/views/comments/create.js.erb
<% if @comment.valid? %>
console.log("before: ", $("#comments article"))
$("<%= escape_javascript(render 'comment', comment: @comment) %>").prependTo("#comments");
//$("<h2>Hello</h2>").prependTo("#comments");
console.log("after: ", $("#comments article"))
<% end %>

$("#new_comment").html("<%= escape_javascript(render "comments/new") %>")

app/views/comments/edit.html.erb
<div class="page-header">
  <%= link_to comments_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @comment, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing comment</h1>
</div>

<%= render 'form' %>

app/views/comments/index.html.erb
<div class="page-header">
  <%= link_to new_comment_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Comment
  <% end %>
  <h1>Listing comments</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Author</th>
            <th>Post</th>
            <th>Body</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @comments) do |comment| %>
            <td><%= comment.author %></td>
            <td><%= comment.post %></td>
            <td><%= comment.body %></td>
            <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/comments/new.html.erb
<div class="page-header">
  <%= link_to comments_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New comment</h1>
</div>

<%= render 'form' %>

app/views/comments/show.html.erb
<div class="page-header">
  <%= link_to comments_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_comment_path(@comment), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show comment</h1>
</div>

<dl class="dl-horizontal">
  <dt>Author:</dt>
  <dd><%= @comment.author %></dd>

  <dt>Post:</dt>
  <dd><%= @comment.post %></dd>

  <dt>Body:</dt>
  <dd><%= @comment.body %></dd>

</dl>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Project', root_path, :class => 'navbar-brand' %>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to('', '#') %></li>
        <li><%= link_to('', '#') %></li>
        <li><%= link_to('', '#') %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li><%= link_to('My Account', edit_user_registration_path) %></li>
            <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
        <% else %>
            <li><%= link_to('Sign in', new_user_session_path) %></li>
            <li><%= link_to('Sign up', new_user_registration_path) %></li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container-fluid -->
</nav>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
    <li><%= link_to('My Account', edit_user_registration_path) %></li>
    <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
<% else %>
    <li><%= link_to('Sign in', new_user_session_path) %></li>
    <li><%= link_to('Sign up', new_user_registration_path) %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Barebones" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Barebones" %>">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <%= render 'layouts/navigation' %>
</header>
<main role="main">
    <div class="col-xs-8 col-xs-offset-2 col-md-9 col-md-offset-1">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
</main>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@edit_post, html: {class: "form-horizontal", role: "form"}, remote: true) do |f| %>
    <% if @edit_post.errors.any? %>
        <div class="alert alert-danger alert-dismissable" role="alert">
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4><%= pluralize(@edit_post.errors.count, "error") %> prohibited this edit_post from being saved:</h4>

          <ul>
            <% @edit_post.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :title, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :title, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :body, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_area :body, class: "form-control", rows: 6 %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :publish_date, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <div class="input-group date col-sm-9" data-provide="datepicker">
          <%= f.text_field :publish_date, class: "form-control" %>
          <!--<input type="text" class="form-control">-->
          <div class="input-group-addon">
            <span class="glyphicon glyphicon-th"></span>
          </div>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: "btn btn-primary" %>
      </div>
    </div>

    <%= f.hidden_field(:author_id) %>
    <%= f.hidden_field(:publish_date) %>
<% end %>

app/views/posts/_post.html.erb
<div class="post panel panel-default">
  <div class="panel-heading">
    <div class="clearfix">

      <% if local_assigns.fetch(:hide_link, false) %>
          <h2>
            <div class="btn-group pull-right">
              <%= link_to posts_path, class: 'btn btn-default' do %>
                  <span class="glyphicon glyphicon-list-alt"></span>
                  Back
              <% end %>
              <%= link_to edit_post_path(@post), class: 'btn btn-primary' do %>
                  <span class="glyphicon glyphicon-pencil"></span>
                  Edit
              <% end %>
            </div>
            <%= post.title %>
          </h2>
      <% else %>
          <h2><%= link_to post.title, post %></h2>
      <% end %>
      <small style="padding-bottom: 6px"><%= post.byline %></small>
    </div>
  </div>

  <article class="clearfix panel-body" id="<%= post.id %>">

    <div><%= post.body.gsub("\n", '<br/>').html_safe %></div>
    <h5>Comments: <%= post.comments.count %></h5>
  </article>
</div>

app/views/posts/create.js.erb
<% if @post.valid? %>
  $("<%= escape_javascript(render @post) %>").prependTo("#posts");
  $("#new_post").toggle();
<% end %>

$("#new_post").html("<%= escape_javascript(render "form") %>")

app/views/posts/edit.html.erb
<div class="page-header">
  <%= link_to posts_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @post, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing <%= @post.title %></h1>
</div>

<%= render 'form' %>

app/views/posts/index.html.erb
<div class="col-md-8">
  <div class="page-header">
    <%= link_to new_post_path, method: "get", class: 'btn btn-primary', remote: true do %>
        <span class="glyphicon glyphicon-plus"></span>
        New Post
    <% end %>
    <h1>Listing posts</h1>
    <%= paginate @posts, :theme => 'twitter-bootstrap-3' %>
  </div>

  <div id="new_post" style="display: none;">
    <%= render "form", object: @new_post %>
  </div>
  <div id="posts" class="table-responsive">
    <%= render @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="page-header">
  <%= link_to posts_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New post</h1>
</div>

<%= render 'form' %>

app/views/posts/new.js.erb
$("#new_post").toggle();

app/views/posts/show.html.erb
<%= render @post, hide_link: true %>


<div  class="col-md-12" >

  <%= render 'comments/new' %>

</div>

<div id="comments" class="clearfix col-md-12" style="min-height: 400px">
  <%= render 'comments/comments_panel', comments: @comments %>
</div>

app/views/posts/show.js.erb
$("#comments").html("<%= escape_javascript(render 'comments/comments_panel', comments:  @comments) %>");